# --- NASTAVENÍ SÍTĚ ---
network:
  yeelights:
    - ip: "192.168.10.112"
      name: "Žárovka 1"
    - ip: "192.168.10.113"
      name: "Žárovka 2"
    - ip: "192.168.10.114"
      name: "Žárovka 3"
    - ip: "192.168.10.115"
      name: "Žárovka 4"
    - ip: "192.168.10.111"
      name: "Praha Byt"

# --- NASTAVENÍ VSTUPU ---
input:
  # Název zařízení nebo část názvu klávesnice/keypadu (např. "Compx 2.4G Receiver").
  # Ponech "auto" nebo prázdné pro automatickou detekci.
  device_name: "Compx 2.4G Receiver"

# --- NASTAVENÍ ZVUKU ---
audio:
  folder: "audio/"
  volume: 1.0

bulbs:
  normal_color:
    kelvin: 3200
  evil_colors:
    - r: 255
      g: 0
      b: 0
    - r: 235
      g: 0
      b: 235
    - r: 0
      g: 0
      b: 255
    - r: 0
      g: 255
      b: 0

