# --- NASTAVENÍ SÍTĚ ---
network:
  yeelights:
    - ip: "192.168.1.101"
      name: "Žárovka 1"
    - ip: "192.168.1.102"
      name: "Žárovka 2"
    - ip: "192.168.1.103"
      name: "Žárovka 3"
    - ip: "192.168.1.104"
      name: "Žárovka 4"

# --- NASTAVENÍ ZVUKU ---
audio:
  bgm_folder: "audio/bgm/"
  sfx_folder: "audio/sfx/"