# --- NASTAVENÍ SÍTĚ ---
network:
  yeelights:
    - ip: "192.168.10.111"
      name: "Žárovka 1"
    - ip: "192.168.10.113"
      name: "Žárovka 2"
    - ip: "192.168.10.114"
      name: "Žárovka 3"
    - ip: "192.168.10.115"
      name: "Žárovka 4"

# --- NASTAVENÍ ZVUKU ---
audio:
  bgm_folder: "audio/bgm/"
  sfx_folder: "audio/sfx/"
  volume: 0.5

bulbs:
  evil_colors:
    - r: 255
      g: 0
      b: 0
    - r: 255
      g: 128
      b: 0
    - r: 255
      g: 0
      b: 255
    - r: 0
      g: 0
      b: 255
    - r: 0
      g: 255
      b: 0

